### ISSUE TITLE
Error when running training for player_backhand_detector

### ISSUE THREAD

**Issue by yosuaalvin** [jerrykal/AI_CUP_2023_Spring_Computer_Vision#2]
when i run the training of player_backhand_detector there is an error
Traceback (most recent call last):
  File "/media/labkom/NewVolume/Badminton/AI_CUP_2023_Spring_Computer_Vision/src/player_backhand_detector/train.py", line 237, in <module>
    main(args)
  File "/media/labkom/NewVolume/Badminton/AI_CUP_2023_Spring_Computer_Vision/src/player_backhand_detector/train.py", line 64, in main
    features = load_features(
  File "/media/labkom/NewVolume/Badminton/AI_CUP_2023_Spring_Computer_Vision/src/player_backhand_detector/dataset.py", line 66, in load_features
    [
  File "/media/labkom/NewVolume/Badminton/AI_CUP_2023_Spring_Computer_Vision/src/player_backhand_detector/dataset.py", line 71, in <listcomp>
    *df_pose.loc[fnum].values[1:-1]
  File "/home/labkom/anaconda3/envs/aicup/lib/python3.9/site-packages/pandas/core/indexing.py", line 1192, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/home/labkom/anaconda3/envs/aicup/lib/python3.9/site-packages/pandas/core/indexing.py", line 1432, in _getitem_axis
    return self._get_label(key, axis=axis)
  File "/home/labkom/anaconda3/envs/aicup/lib/python3.9/site-packages/pandas/core/indexing.py", line 1382, in _get_label
    return self.obj.xs(label, axis=axis)
  File "/home/labkom/anaconda3/envs/aicup/lib/python3.9/site-packages/pandas/core/generic.py", line 4295, in xs
    loc = index.get_loc(key)
  File "/home/labkom/anaconda3/envs/aicup/lib/python3.9/site-packages/pandas/core/indexes/range.py", line 415, in get_loc
    raise KeyError(key) from err
KeyError: 604

**Comment by jerrykal** [comment]
This error is likely due to the lack of dataset, as I commented from the last issue, I can't provide and do not have the dataset anymore. This repo was just meant to be a showcase for the competition's presentation. It will not run without the correct data.

**Comment by yosuaalvin** [comment]
the dataset still exist in https://github.com/wish44165/A-New-Perspective-for-Shuttlecock-Hitting-Event-Detection please try
